DROP DATABASE IF EXISTS newsservice;
DROP USER IF EXISTS `news_service`@`%`;
CREATE DATABASE IF NOT EXISTS newsservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `news_service`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW,
SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `newsservice`.* TO `news_service`@`%`;
FLUSH PRIVILEGES;